collision_model_parameters:
  padding: 0
  links_with_padding: []
  blacklist:
    leg_joints:
      - first: leg_right_1_link
        second: left_sole_link
      - first: leg_right_2_link
        second: left_sole_link
      - first: leg_left_1_link
        second: right_sole_link
      - first: leg_left_2_link
        second: right_sole_link
      - first: leg_right_2_link
        second: leg_left_1_link
      - first: leg_left_2_link
        second: leg_right_1_link
      - first: leg_left_1_link
        second: leg_left_3_link
      - first: leg_left_3_link
        second: leg_left_1_link
      - first: leg_right_1_link
        second: leg_right_3_link
      - first: leg_right_3_link
        second: leg_right_1_link
      - first: leg_right_3_link
        second: leg_right_knee_link
      - first: leg_left_3_link
        second: leg_left_knee_link
      - first: leg_right_4_link
        second: leg_right_knee_link
      - first: leg_right_5_link
        second: leg_right_knee_link
      - first: leg_left_4_link
        second: leg_left_knee_link
      - first: leg_left_5_link
        second: leg_left_knee_link
      - first: leg_right_1_link
        second: leg_right_femur_link
      - first: leg_left_1_link
        second: leg_left_femur_link
      - first: base_link
        second: torso_link
      - first: base_link
        second: back_handle
      - first: torso_link
        second: back_handle
      - first: leg_left_1_link
        second: back_handle
      - first: leg_right_1_link
        second: back_handle
      - first: pelvis_base_link
        second: back_handle
      - first: pelvis_1_link
        second: back_handle
      - first: pelvis_2_link 
        second: back_handle
      - first: torso_link
        second: leg_right_1_link
      - first: torso_link
        second: leg_left_1_link
      - first: base_link
        second: leg_right_1_link
      - first: base_link
        second: leg_left_1_link
      - first: base_link
        second: waist_front_rgbd_camera_link
      - first: base_link
        second: waist_back_rgbd_camera_link
      - first: torso_link
        second: torso_front_rgbd_camera_link
      - first: torso_link
        second: torso_back_rgbd_camera_link
      - first: leg_left_1_link
        second: waist_protector
      - first: leg_right_1_link
        second: waist_protector
      - first: torso_link
        second: waist_front_rgbd_camera_link
      - first: torso_link
        second: waist_back_rgbd_camera_link
      - first: torso_link
        second: waist_protector
      - first: waist_front_rgbd_camera_link
        second: waist_protector
      - first: waist_back_rgbd_camera_link
        second: waist_protector
    pelvis_joints:
      - first: base_link
        second: pelvis_base_link
      - first: base_link
        second: pelvis_1_link
      - first: base_link
        second: pelvis_2_link
      - first: pelvis_base_link
        second: pelvis_1_link
      - first: pelvis_base_link
        second: pelvis_2_link
      - first: pelvis_base_link
        second: torso_link
      - first: pelvis_1_link
        second: pelvis_2_link
      - first: pelvis_1_link
        second: torso_link
      - first: pelvis_2_link
        second: torso_link
      - first: leg_right_1_link
        second: pelvis_base_link
      - first: leg_right_2_link
        second: pelvis_base_link
      - first: leg_left_1_link
        second: pelvis_base_link
      - first: leg_left_2_link
        second: pelvis_base_link
      - first: leg_right_1_link
        second: pelvis_1_link
      - first: leg_right_2_link
        second: pelvis_1_link
      - first: leg_left_1_link
        second: pelvis_1_link
      - first: leg_left_2_link
        second: pelvis_1_link
    arms_joints:
      - first: torso_link
        second: arm_left_base_link
      - first: torso_link
        second: arm_right_base_link
      - first: torso_link
        second: arm_right_1_link
      - first: torso_link
        second: arm_left_1_link
      - first: arm_left_base_link
        second: arm_left_1_link
      - first: arm_left_1_link
        second: arm_left_2_link
      - first: arm_left_2_link
        second: arm_left_3_link
      - first: arm_left_3_link
        second: arm_left_4_link
      - first: arm_left_4_link
        second: arm_left_5_link
      - first: arm_left_5_link
        second: arm_left_6_link
      - first: arm_left_6_link
        second: arm_left_7_link

      - first: arm_left_7_link
        second: gripper_left_base_link
      - first: gripper_left_fingertip_right_link
        second: gripper_left_fingertip_left_link
      - first: gripper_left_fingertip_right_link
        second: gripper_left_inner_finger_right_link
      - first: gripper_left_fingertip_right_link
        second: gripper_left_outer_finger_right_link
      - first: gripper_left_fingertip_right_link
        second: gripper_left_base_link
      - first: gripper_left_inner_finger_right_link
        second: gripper_left_outer_finger_right_link
      - first: gripper_left_inner_finger_right_link
        second: gripper_left_base_link
      - first: gripper_left_base_link
        second: gripper_left_outer_finger_right_link

      - first: gripper_left_fingertip_right_link
        second: gripper_left_fingertip_left_link
      - first: gripper_left_fingertip_left_link
        second: gripper_left_inner_finger_left_link
      - first: gripper_left_fingertip_left_link
        second: gripper_left_outer_finger_left_link
      - first: gripper_left_fingertip_left_link
        second: gripper_left_base_link
      - first: gripper_left_inner_finger_left_link
        second: gripper_left_outer_finger_left_link
      - first: gripper_left_inner_finger_left_link
        second: gripper_left_base_link
      - first: gripper_left_base_link
        second: gripper_left_outer_finger_left_link

      - first: arm_right_base_link
        second: arm_right_1_link
      - first: arm_right_1_link
        second: arm_right_2_link
      - first: arm_right_2_link
        second: arm_right_3_link
      - first: arm_right_3_link
        second: arm_right_4_link
      - first: arm_right_4_link
        second: arm_right_5_link
      - first: arm_right_5_link
        second: arm_right_6_link
      - first: arm_right_6_link
        second: arm_right_7_link
      - first: arm_right_7_link
        second: gripper_right_base_link

      - first: gripper_right_fingertip_right_link
        second: gripper_right_fingertip_left_link
      - first: gripper_right_fingertip_right_link
        second: gripper_right_inner_finger_right_link
      - first: gripper_right_fingertip_right_link
        second: gripper_right_outer_finger_right_link
      - first: gripper_right_fingertip_right_link
        second: gripper_right_base_link
      - first: gripper_right_inner_finger_right_link
        second: gripper_right_outer_finger_right_link
      - first: gripper_right_inner_finger_right_link
        second: gripper_right_base_link
      - first: gripper_right_base_link
        second: gripper_right_outer_finger_right_link

      - first: gripper_right_fingertip_right_link
        second: gripper_right_fingertip_left_link
      - first: gripper_right_fingertip_left_link
        second: gripper_right_inner_finger_left_link
      - first: gripper_right_fingertip_left_link
        second: gripper_right_outer_finger_left_link
      - first: gripper_right_fingertip_left_link
        second: gripper_right_base_link
      - first: gripper_right_inner_finger_left_link
        second: gripper_right_outer_finger_left_link
      - first: gripper_right_inner_finger_left_link
        second: gripper_right_base_link
      - first: gripper_right_base_link
        second: gripper_right_outer_finger_left_link

