zeros:
  arm_left_1_joint:                   0.24
  arm_left_2_joint:                   1.26
  arm_left_3_joint:                   1.57
  arm_left_4_joint:                   0.8
  arm_left_5_joint:                   0.0
  arm_left_6_joint:                   0.0
  arm_left_7_joint:                   0.0
  arm_right_1_joint:                  -0.24
  arm_right_2_joint:                  1.26
  arm_right_3_joint:                  -1.57
  arm_right_4_joint:                  0.8
  arm_right_5_joint:                  0.0
  arm_right_6_joint:                  0.0
  arm_right_7_joint:                  0.0
  pelvis_1_joint:                     0.0
  pelvis_2_joint:                     0.0
  leg_left_1_joint:                   -0.012
  leg_left_2_joint:                   0.054
  leg_left_3_joint:                   0.04
  leg_left_4_joint:                   -0.053
  leg_left_5_joint:                   0.0
  leg_left_length_joint:              0.6
  leg_left_femur_joint:               0.9
  leg_left_knee_joint:                1.8
  leg_right_1_joint:                  0.012
  leg_right_2_joint:                  0.054
  leg_right_3_joint:                  -0.04
  leg_right_4_joint:                  -0.053
  leg_right_5_joint:                  0.0
  leg_right_length_joint:             0.6
  leg_right_femur_joint:              0.9
  leg_right_knee_joint:               1.8

default_floating_base_pose:
  orientation:
    x: 0.
    y: 0.
    z: 0.
    w: 1.
  position: [0., 0., 0.86]
