${ARM_SIDE_PREFIX}_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    open_loop_control: true
    joints:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      ${ARM_SIDE_PREFIX}_1_joint:
        goal: 0.02
      ${ARM_SIDE_PREFIX}_2_joint:
        goal: 0.02
      ${ARM_SIDE_PREFIX}_3_joint:
        goal: 0.02
      ${ARM_SIDE_PREFIX}_4_joint:
        goal: 0.02
      ${ARM_SIDE_PREFIX}_5_joint:
        goal: 0.02
      ${ARM_SIDE_PREFIX}_6_joint:
        goal: 0.02
      ${ARM_SIDE_PREFIX}_7_joint:
        goal: 0.02
