${LEG_SIDE_PREFIX}_position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    open_loop_control: true
    joints:
      - ${LEG_SIDE_PREFIX}_1_joint
      - ${LEG_SIDE_PREFIX}_2_joint
      - ${LEG_SIDE_PREFIX}_3_joint
      - ${LEG_SIDE_PREFIX}_length_joint
      - ${LEG_SIDE_PREFIX}_4_joint
      - ${LEG_SIDE_PREFIX}_5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      ${LEG_SIDE_PREFIX}_1_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_2_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_3_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_4_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_5_joint:
        goal: 0.02