pelvis_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    open_loop_control: true
    joints:
      - pelvis_1_joint
      - pelvis_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0 # FIXME: See #8429
      pelvis_1_joint:
        goal: 0.02
      pelvis_2_joint:
        goal: 0.02