gains:
  leg_left_1_joint: &leg_1_gains {p: 5000,  d: 0, i: 0, i_clamp: 50, torque_clamp: 50}
  leg_left_2_joint: &leg_2_gains {p: 5000,  d: 50, i: 0, i_clamp: 50, torque_clamp: 50}
  leg_left_3_joint: &leg_3_gains {p: 5000,  d: 100, i: 5, i_clamp: 50, torque_clamp: 50}
  leg_left_length_joint: &leg_length_gains {p: 100000,  d: 5, i: 100, i_clamp: 50, torque_clamp: 50}
  leg_left_4_joint: &leg_4_gains {p: 1000, d: 0, i: 10, i_clamp: 10, torque_clamp: 50}
  leg_left_5_joint: &leg_5_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  leg_right_1_joint: *leg_1_gains
  leg_right_2_joint: *leg_2_gains
  leg_right_3_joint: *leg_3_gains
  leg_right_length_joint: *leg_length_gains
  leg_right_4_joint: *leg_4_gains
  leg_right_5_joint: *leg_5_gains
  pelvis_1_joint: {p: 5000,  d: 0, i: 0, i_clamp: 50, torque_clamp: 50}
  pelvis_2_joint: {p: 5000,  d: 0, i: 0, i_clamp: 50, torque_clamp: 50}
  arm_left_1_joint: &arm_1_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_left_2_joint: &arm_2_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_left_3_joint: &arm_3_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_left_4_joint: &arm_4_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_left_5_joint: &arm_5_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_left_6_joint: &arm_6_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_left_7_joint: &arm_7_gains {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  gripper_left_finger_joint: &gripper_left_finger_joint {p: 500, d: 0.5, i: 2, i_clamp: 10, torque_clamp: 50}
  arm_right_1_joint: *arm_1_gains
  arm_right_2_joint: *arm_2_gains
  arm_right_3_joint: *arm_3_gains
  arm_right_4_joint: *arm_4_gains
  arm_right_5_joint: *arm_5_gains
  arm_right_6_joint: *arm_6_gains
  arm_right_7_joint: *arm_7_gains
  gripper_right_finger_joint: *gripper_left_finger_joint
