/**:
  ros__parameters:
    motions:
      crouch_box:
        joints:
        - leg_left_1_joint
        - leg_left_2_joint
        - leg_left_3_joint
        - leg_left_length_joint
        - leg_left_4_joint
        - leg_left_5_joint
        - leg_right_1_joint
        - leg_right_2_joint
        - leg_right_3_joint
        - leg_right_length_joint
        - leg_right_4_joint
        - leg_right_5_joint
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint
        times_from_start:
        - 0.0
        - 3.0
        - 6.0
        positions:
        - 0.0
        - 0.05
        - 0.0
        - 0.655
        - -0.05
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.655
        - -0.05
        - 0.0
        - -0.5696
        - 1.71
        - 1.6694
        - 1.188
        - 0.0
        - 0.0
        - 0.0
        - 0.56522
        - 1.71
        - -1.6699
        - 1.1892
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.355
        - -0.05
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.355
        - -0.05
        - 0.0
        - -0.5696
        - 1.71
        - 1.6694
        - 1.188
        - 0.0
        - 0.0
        - 0.0
        - 0.56522
        - 1.71
        - -1.6699
        - 1.1892
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.18
        - -0.05
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.18
        - -0.05
        - 0.0
        - -0.5696
        - 1.71
        - 1.6694
        - 1.188
        - 0.0
        - 0.0
        - 0.0
        - 0.56522
        - 1.71
        - -1.6699
        - 1.1892
        - 0.0
        - 0.0
        - 0.0
        meta:
          name: crouch_box
          usage: ''
          description: crouch with a box
      standup_box:
        joints:
        - leg_left_1_joint
        - leg_left_2_joint
        - leg_left_3_joint
        - leg_left_length_joint
        - leg_left_4_joint
        - leg_left_5_joint
        - leg_right_1_joint
        - leg_right_2_joint
        - leg_right_3_joint
        - leg_right_length_joint
        - leg_right_4_joint
        - leg_right_5_joint
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint
        times_from_start:
        - 0.0
        - 3.0
        - 6.0
        positions:
        - 0.0
        - 0.05
        - 0.0
        - 0.18
        - -0.05
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.18
        - -0.05
        - 0.0
        - -0.5696
        - 1.71
        - 1.6694
        - 1.188
        - 0.0
        - 0.0
        - 0.0
        - 0.56522
        - 1.71
        - -1.6699
        - 1.1892
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.355
        - -0.05
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.355
        - -0.05
        - 0.0
        - -0.5696
        - 1.71
        - 1.6694
        - 1.188
        - 0.0
        - 0.0
        - 0.0
        - 0.56522
        - 1.71
        - -1.6699
        - 1.1892
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.655
        - -0.05
        - 0.0
        - 0.0
        - 0.05
        - 0.0
        - 0.655
        - -0.05
        - 0.0
        - -0.5696
        - 1.71
        - 1.6694
        - 1.188
        - 0.0
        - 0.0
        - 0.0
        - 0.56522
        - 1.71
        - -1.6699
        - 1.1892
        - 0.0
        - 0.0
        - 0.0
        meta:
          name: standup_box
          usage: ''
          description: Move to standup configuration with box
      ground_pushups:
        joints:
        - leg_left_1_joint
        - leg_left_2_joint
        - leg_left_3_joint
        - leg_left_length_joint
        - leg_left_4_joint
        - leg_left_5_joint
        - leg_right_1_joint
        - leg_right_2_joint
        - leg_right_3_joint
        - leg_right_length_joint
        - leg_right_4_joint
        - leg_right_5_joint
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint
        times_from_start:
        - 0.0
        - 1.0
        - 2.0
        - 4.0
        - 5.0
        - 6.0
        - 8.0
        positions:
        - 0.0
        - 0.45
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.45
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.4
        - 1.32
        - -1.5707
        - 2.4
        - 0.0
        - 0.0
        - 0.0
        - -0.4
        - 1.32
        - 1.5701
        - 2.4
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.6
        - 1.0
        - -2.2707
        - 2.0
        - 0.0
        - 0.0
        - 0.0
        - -0.6
        - 1.0
        - 2.2701
        - 2.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 1.2
        - 1.0
        - -2.2707
        - 1.4
        - 0.0
        - 0.0
        - 0.0
        - -1.2
        - 1.0
        - 2.2701
        - 1.4
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.45
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.45
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.4
        - 1.0
        - -2.2707
        - 2.4
        - 0.0
        - 0.0
        - 0.0
        - -0.4
        - 1.0
        - 2.2701
        - 2.4
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.6
        - 1.0
        - -2.2707
        - 2.0
        - 0.0
        - 0.0
        - 0.0
        - -0.6
        - 1.0
        - 2.2701
        - 2.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.25
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 1.2
        - 1.0
        - -2.2707
        - 1.4
        - 0.0
        - 0.0
        - 0.0
        - -1.2
        - 1.0
        - 2.2701
        - 1.4
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.45
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.0
        - 0.45
        - 0.0
        - 0.135
        - 0.0
        - 0.0
        - 0.4
        - 1.32
        - -1.5707
        - 2.4
        - 0.0
        - 0.0
        - 0.0
        - -0.4
        - 1.32
        - 1.5701
        - 2.4
        - 0.0
        - 0.0
        - 0.0
        meta:
          name: ground_pushups
          usage: ''
          description: Pushups from ground position
      