/**:
  ros__parameters:
    motion_planner:
      disable_motion_planning: false
      planning_groups: # Sorted by order of preference
        - full
        - both_legs
        - leg_right
        - leg_left
        - pelvis
      joint_tolerance: 0.01

      # Parameters for non-planned approach
      approach_velocity: 0.5
      approach_min_duration: 0.5